version: '3.8'

services:
  app-svc:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    ports:
      - '${APP_PORT}:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
      - redis

  db:
    image: docker.io/library/postgres:latest
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:7
    ports:
      - '${REDIS_APP_PORT}:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]      
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: