version: '3.8'

services:
  app:
    image: "${APP_IMAGE:-nestjs-app}:prod-latest"
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PROD_HOST_PORT:-3002}:${APP_PORT:-3000}"
    command: ["node", "dist/main.js"]
    depends_on:
      - db
      - redis          